### PR TITLE
Login page - shared CSS

### PR DESCRIPTION
**Pull request by rob-kendrick**
Added basic shared scss variables for themes, ubuntu  font

### CODE REVIEW

**Comment by rob-kendrick** [comment]
yo some of the shared css page is messy but dw because i already fixed it for the next commit

**Comment by blavejr** [comment]
Sweet, push it. I'm taking a look right now.

**Comment by blavejr** [comment]
You can still push new changes after you've created the PR

**Review by blavejr — APPROVED** [review]
This is fire brov, I'll approve it but if you have more changes push otherwise feel free to merge 🔥

**Pull request merged**
